<a href="https://www.kaggle.com/code/sjagkoo7/numpy-pandas-matplotlib-seaborn?scriptVersionId=270822808" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/nifty50-stock-market-data/HDFCBANK.csv
/kaggle/input/nifty50-stock-market-data/GRASIM.csv
/kaggle/input/nifty50-stock-market-data/WIPRO.csv
/kaggle/input/nifty50-stock-market-data/stock_metadata.csv
/kaggle/input/nifty50-stock-market-data/BPCL.csv
/kaggle/input/nifty50-stock-market-data/INFY.csv
/kaggle/input/nifty50-stock-market-data/LT.csv
/kaggle/input/nifty50-stock-market-data/RELIANCE.csv
/kaggle/input/nifty50-stock-market-data/BRITANNIA.csv
/kaggle/input/nifty50-stock-market-data/INFRATEL.csv
/kaggle/input/nifty50-stock-market-data/HEROMOTOCO.csv
/kaggle/input/nifty50-stock-market-data/HINDUNILVR.csv
/kaggle/input/nifty50-stock-market-data/TATAMOTORS.csv
/kaggle/input/nifty50-stock-market-data/MM.csv
/kaggle/input/nifty50-stock-market-data/HDFC.csv
/kaggle/input/nifty50-stock-market-data/JSWSTEEL.csv
/kaggle/input/nifty50-stock-market-data/TITAN.csv
/kaggle/input/nifty50-stock-market-data/HINDALCO.csv
/kaggle/input/nifty50-stock-market-data/AXISBANK.csv
/kaggle/inpu

In [2]:
# just data reading
#data = pd.read_csv("/kaggle/input/factors-affecting-campus-placement/Placement_Data_Full_Class.csv")
data = pd.read_csv("/kaggle/input/nifty50-stock-market-data/TCS.csv")
data.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


Date Symbol Series  Prev Close    Open    High     Low    Last  \
0  2004-08-25    TCS     EQ      850.00  1198.7  1198.7  979.00  985.00   
1  2004-08-26    TCS     EQ      987.95   992.0   997.0  975.30  976.85   
2  2004-08-27    TCS     EQ      979.00   982.4   982.4  958.55  961.20   
3  2004-08-30    TCS     EQ      962.65   969.9   990.0  965.00  986.40   
4  2004-08-31    TCS     EQ      986.75   986.5   990.0  976.00  987.80   

    Close     VWAP    Volume      Turnover  Trades  Deliverable Volume  \
0  987.95  1008.32  17116372  1.725876e+15     NaN             5206360   
1  979.00   985.65   5055400  4.982865e+14     NaN             1294899   
2  962.65   969.94   3830750  3.715586e+14     NaN              976527   
3  986.75   982.65   3058151  3.005106e+14     NaN              701664   
4  988.10   982.18   2649332  2.602133e+14     NaN              695234   

   %Deliverble  
0       0.3042  
1       0.2561  
2       0.2549  
3       0.2294  
4       0.2624

# Numpy +  Pandas

In [3]:
#help(np.array)
#help(np.arange)

In [4]:
def numpy_explore_part1():
    '''
    NumPy was created in 2005 by Travis Oliphant. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists. 
    NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
    This behavior is called locality of reference in computer science. It also has functions for working in domain of linear algebra, fourier transform, and matrices.")
    '''
    print("Welcome to Numpy Learning .......!")
    print(f"numpy version : {np.__version__}")
    
    # ---------------------- np.array --------------------------------
    print("\n---------------- np.array using list -------------------")
    numpy_list = np.array([1,2,3,4,5]) 
    print(f"numpy array using list : {numpy_list}")
    print(f"numpy_list  type : {type(numpy_list)}")
    print(f"numpy_list  dimension : {numpy_list.ndim}")

    print("\n---------------- np.array using tuple -------------------")
    numpy_tuple = np.array((1,2,3,4,5),dtype = float)
    print(f"numpy array using tuple : {numpy_tuple}")
    print(f"numpy_tuple  type : {type(numpy_tuple)}")
    print(f"numpy_tuple  dimension : {numpy_tuple.ndim}")
    
    print("\n---------------- 2-D array -------------------")
    two_D_array = np.array([[1,2,3,4],[5,6,7,8]])
    print(f"2-D numpy array : \n {two_D_array}")
    print(f"2-D numpy array  dimension : {two_D_array.ndim}")

    print("\n---------------- 3-D array -------------------")
    three_D_array =np.array([[[1,2,3,4],[5,6,7,8]] ,[[9,0,11,12],[14,15,16,17]]])
    print(f"3-D numpy array : \n {three_D_array}")
    
    print("\n---------------- Understading Indexing -------------------")
    print(f"Element on the 2nd row, 4th column in two_D_array : {two_D_array[1,3]}")
    print(f"Access the third element of the second array of the first array:{three_D_array[0,1,2]}")
    print(f"sum of {numpy_list[1]} , {numpy_tuple[2]} and {two_D_array[0][3]}  : {numpy_list[1]+ numpy_tuple[2]+two_D_array[0][3]}")
    

    print("\n------------- Slicing [start:end:step] ----------------------------")
    print(f"accessing element from last : {numpy_list[::-1]}")
    print(f"Slicing with step 2 Original : {numpy_list} Post slicing : {numpy_list[1:4:2]}")
    print(f"2-D slicing :\n{ two_D_array[0:2, 1:3]}")
    
    arr = np.array([[1,2,3,4],[8,9,10,11],[2,3,4,5],[11,12,13,14]])
    print(f"jumping by step 2 for row :\n{arr[:3:2,0:1]}")
    print(f"jumping by step 2 for row and column :\narr{arr[:3:2,0:3:2]}")
    print(f"accessing element in reverse in 2-D numpy array:\n{arr[-1:,:]}")

    print("\n------------------- Broadcasting -----------------------------")
    array_broad1 = np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13],[21,22,23,23]])
    array_broad2 = np.array([[1],[2],[3],[4]])
    result = array_broad1*array_broad2
    print(f"Broadcasting {array_broad1.shape} and {array_broad2.shape} :\n {result}")
    
    return None

#program execution starts from here
if __name__ ==  "__main__":
    numpy_explore_part1()

Welcome to Numpy Learning .......!
numpy version : 1.26.4

---------------- np.array using list -------------------
numpy array using list : [1 2 3 4 5]
numpy_list  type : <class 'numpy.ndarray'>
numpy_list  dimension : 1

---------------- np.array using tuple -------------------
numpy array using tuple : [1. 2. 3. 4. 5.]
numpy_tuple  type : <class 'numpy.ndarray'>
numpy_tuple  dimension : 1

---------------- 2-D array -------------------
2-D numpy array : 
 [[1 2 3 4]
 [5 6 7 8]]
2-D numpy array  dimension : 2

---------------- 3-D array -------------------
3-D numpy array : 
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9  0 11 12]
  [14 15 16 17]]]

---------------- Understading Indexing -------------------
Element on the 2nd row, 4th column in two_D_array : 8
Access the third element of the second array of the first array:7
sum of 2 , 3.0 and 4  : 9.0

------------- Slicing [start:end:step] ----------------------------
accessing element from last : [5 4 3 2 1]
Slicing with step 2 Original

In [5]:
def numpy_explore_part2():
    '''
    copy vs view : copy refer as new object , any change in copied numpy won't effect on original numpy array. 
    However, view will affect the original numpy.
    '''
    numpy_array = np.array([1,2,3,4],dtype = float)
    view_numpy_array = numpy_array.view()
    view_numpy_array[1] = 20
    print(f'original array after view : {numpy_array} and view array : {view_numpy_array}')

    '''
    shape vs reshape : shape to check the dimension where reshpae is reshape the numpy array.
    '''
    shape_numpy = np.array ([1,2,3,4,5],dtype  = float , ndmin=5)
    print(f"\ncreating 5-D numpy array: {shape_numpy} and dimension of array :{shape_numpy.shape}")
    shape_numpy_1 = np.array ([1,2,3,4],dtype  = float , ndmin=5)
    print(f"creating 5-D numpy array: {shape_numpy_1} and dimension of array :{shape_numpy_1.shape}")
    
    try :
        single_array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
        print(f"convert 1-D numpy array in 2-D numpy array :\n{single_array.reshape(3,4)}")
        print(f"connvert 1-D numpy array to 3-D numpy array:\n{single_array.reshape(2,3,2)}")
        print(f"convert 1-D numpy array in 2-D numpy array shape is wrong :\n{single_array.reshape(3,5)}")
        #print(f"convert 1-D numpy array in 2-D numpy array :\n{single_array.reshape(3,a)}")
    except ValueError: 
        print("There is error in reshape please check ")
    except Exception as e:
        print(e)

    '''Creating Identity Matrix'''
    print(f"\nCreating 3x3 identity Matrix :\n{np.eye(3)}")

    '''np.arange([start,] stop[, step], dtype=None)'''
    print("\n------------- np.arange([start,] stop[, step], dtype=None) ----------------------------")
    array1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
    array2 = np.array([0,2,0,1]) # this will serve as column index
    array3 = array1[np.arange(4),array2]
    print(array3)
    array1[np.arange(4),array2]+=10
    print(array1)
    
    return None


if __name__ =="__main__":
    numpy_explore_part2()

original array after view : [ 1. 20.  3.  4.] and view array : [ 1. 20.  3.  4.]

creating 5-D numpy array: [[[[[1. 2. 3. 4. 5.]]]]] and dimension of array :(1, 1, 1, 1, 5)
creating 5-D numpy array: [[[[[1. 2. 3. 4.]]]]] and dimension of array :(1, 1, 1, 1, 4)
convert 1-D numpy array in 2-D numpy array :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
connvert 1-D numpy array to 3-D numpy array:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
There is error in reshape please check 

Creating 3x3 identity Matrix :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

------------- np.arange([start,] stop[, step], dtype=None) ----------------------------
[ 1  7  9 14]
[[11  2  3  4]
 [ 5  6 17  8]
 [19 10 11 12]
 [13 24 15 16]]


In [6]:
# -------------------- The Outlier Cleaner --------------------
def clean_outliers(array: np.ndarray) -> np.ndarray:
    
    ''' Function Name: clean outliers(array: np.ndarray) -> np.ndarray
        Description:
        You are given a 1D NumPy array of integers or floats. Replace all outliers (values that are more than 2
        standard deviations away from the mean) with the median of the array. Return the cleaned NumPy array
        after replacement.
        Input:
        • array: a 1D NumPy array of integers or floats
        Output:
        • A NumPy array representing the cleaned version of the input
        Example:
        Input:
        array = np.array([50, 60, 250, 55, 70, 5])
        Output:
        array([50, 60, 70, 55, 70, 55]) , output of third index may not be 70''' 
    
    # Calculate mean, standard deviation, and median
    mean = round(np.mean(array),2)
    std = round(np.std(array),2)
    median = round(np.median(array),2)
    print(f"for debugging mean : {mean}, std : {std} and meadian : {median} ")
    
    # Create a copy of the array to avoid modifying the original
    cleaned_array = array.copy()
    
    # Find outliers (values more than 2 standard deviations from mean) and replace them with the median
    lower_bound = round(mean - 2 * std,2)
    upper_bound = round(mean + 2 * std,2)
    print(f"for debugging lower bound : {lower_bound} and upper_bound : {upper_bound}")
    #approach 1 :
    # new_list = [i if i<upper_bound else median for i in array ]
    # return np.array(new_list,dtype = int)
    
    #approach 2 : using boolean index approach
    outlier_element = (cleaned_array < lower_bound) | (cleaned_array > upper_bound)
    cleaned_array[outlier_element]= median
    print(f"debugging boolean index approach :{outlier_element}\n")
    return cleaned_array
    

if __name__ =="__main__":
    array = np.array([50, 60, 250, 55, 70, 5]) 
    print(clean_outliers(array))

for debugging mean : 81.67, std : 78.03 and meadian : 57.5 
for debugging lower bound : -74.39 and upper_bound : 237.73
debugging boolean index approach :[False False  True False False False]

[50 60 57 55 70  5]


In [7]:
#help(pd.DataFrame)
#a=[1,2,3,4]
# same output
#print(a[:])
#print(a[::])

In [8]:
def pandas_explore_part1():
    '''
    Pandas was created by Wes McKinney in 2008
    '''
    
    print("Welcome to Pandas Learning .......!")
    print(f"pandas version : {pd.__version__}\n")

    # ---------------------- pd.series --------------------------------
    print(f"Pandas Series :\n{pd.Series([3.5,7.2,5.0])}")
    
    print(f"\nPandas Series with custom index:\n{pd.Series([3.5,7.2,5.0],index=['x','y','z'])}")
    
    dic_var = {'Sub1':'Math','sub2':'Python','sub3':'TSA'}
    print(f"\nPandas Series using dictionary :\n{pd.Series(dic_var)}")
    
    print(f"\nPanas Series using custom filter from dictionary :\n{pd.Series(dic_var,index=['Sub1','sub2'])}")

    #----------------------- pd.DataFrame ------------------------------
    student_details = pd.DataFrame({'Name':['Amardeep Kumar','PP Singh','GG Gandhi','TT Singh'],
                 'Course' :['M.TECH AI','P.HD','MBA','B.TECH'],
                 'College':['IIT Madras','IIT Kanpur','IIT Mumbai','IIT Goa'],
                 'Year':['2025','2024','2023','2021'],
                 'Exam Score':[200,300,400,500]},index=['S1','S2','S3','S4'])
    print(f"\nstudent_details dataframe :\n{student_details}")

    #-------loc syntax : df.loc[row_labels, column_labels] -----------------
    person_details = pd.DataFrame({
    "Name": ["Asha", "Bala", "Chetan", "Divya"],
    "Marks": [85, 90, 78, 92],
    "City": ["Chennai", "Pune", "Delhi", "Chennai"]}, index=["s1", "s2", "s3", "s4"])
    
    print(f"\nperson_details dataframe :\n{person_details}")
    
    print(f"\nusing loc :\n{person_details.loc[['s1'],['Name','Marks']]}")
    print(f"\nusing loc with slicing :\n{person_details.loc[:'s3',:]}")
    print(f"\nreversing dataframe using loc:\n{person_details.loc[::-1,::-1]}")
    #print(person_details.loc[[:],[:]]) #gives syntax error
    
    print(f"\napplying filter using loc :\n{person_details.loc[person_details['Marks']>80,['Name','Marks']]}")
    print(f"\n using loc with conidtions :\n{person_details.loc[(person_details['Marks']>80) & (person_details['City'] =='Chennai') ,['Name','Marks','City']]}")
            # applying multiple connditions(lambda) using loc
    Result = person_details.loc[lambda x:(x['Marks']>85) & (x['City']=='Chennai'),['Name','Marks']]
    print(f"\napplying multiple connditions(lambda) using loc:\n {Result}")

    #------- iloc syntax : df.iloc[row_positions, column_positions] ----------------
    print(f"\n Workig with iloc:\n{person_details.iloc[:2,:2]}")

    #-------  query syntax : df.query()--------------------------------------------
    cutoff = 90
    print('Working with query:')
    print(person_details.query('Marks == @cutoff')[['Name','Marks']])
    #help(person_details.query)
    
    return None

if __name__ == "__main__":
    pandas_explore_part1()

Welcome to Pandas Learning .......!
pandas version : 2.2.3

Pandas Series :
0    3.5
1    7.2
2    5.0
dtype: float64

Pandas Series with custom index:
x    3.5
y    7.2
z    5.0
dtype: float64

Pandas Series using dictionary :
Sub1      Math
sub2    Python
sub3       TSA
dtype: object

Panas Series using custom filter from dictionary :
Sub1      Math
sub2    Python
dtype: object

student_details dataframe :
              Name     Course     College  Year  Exam Score
S1  Amardeep Kumar  M.TECH AI  IIT Madras  2025         200
S2        PP Singh       P.HD  IIT Kanpur  2024         300
S3       GG Gandhi        MBA  IIT Mumbai  2023         400
S4        TT Singh     B.TECH     IIT Goa  2021         500

person_details dataframe :
      Name  Marks     City
s1    Asha     85  Chennai
s2    Bala     90     Pune
s3  Chetan     78    Delhi
s4   Divya     92  Chennai

using loc :
    Name  Marks
s1  Asha     85

using loc with slicing :
      Name  Marks     City
s1    Asha     85  Chennai


In [9]:
def pandas_explore_part2():
    student_score = pd.DataFrame({
    "Name": ["Asha", "Bala", "Chetan", "Divya", "Jay"],
    "Marks": [85, 40, 78, 92, 53],
    "City": ["Chennai", "Pune", "Delhi", "Vizag", "Mumbai"]
    })
    student_score.loc[student_score['City']=='Delhi','Marks'] = 80
    print(f"broadcasting ... :\n{student_score}")

    student_score.loc[student_score['Marks']<60,'Marks']+=5
    print(f"broadcasting increasing marks ... :\n{student_score}")

    student_score.loc[lambda x: x['Marks']>90,'Marks'] -=10
    print(f"broadcasting decreasing marks ... :\n{student_score}")

    #------------------------------apply()------------------------------
    student_score['Grade'] = student_score['Marks'].apply(lambda x : "A" if x>85 else ("B" if x>75 else "C"))
    print(f"Broadcasting in Pandas Adding new columns :\n{student_score}")
    
    return None

if __name__ =="__main__":
    pandas_explore_part2()

broadcasting ... :
     Name  Marks     City
0    Asha     85  Chennai
1    Bala     40     Pune
2  Chetan     80    Delhi
3   Divya     92    Vizag
4     Jay     53   Mumbai
broadcasting increasing marks ... :
     Name  Marks     City
0    Asha     85  Chennai
1    Bala     45     Pune
2  Chetan     80    Delhi
3   Divya     92    Vizag
4     Jay     58   Mumbai
broadcasting decreasing marks ... :
     Name  Marks     City
0    Asha     85  Chennai
1    Bala     45     Pune
2  Chetan     80    Delhi
3   Divya     82    Vizag
4     Jay     58   Mumbai
Broadcasting in Pandas Adding new columns :
     Name  Marks     City Grade
0    Asha     85  Chennai     B
1    Bala     45     Pune     C
2  Chetan     80    Delhi     B
3   Divya     82    Vizag     B
4     Jay     58   Mumbai     C


In [10]:
'''Use the following DataFrame as an example to understand the schema for upcoming questions. The actual DataFrame used during testing will have the same structure.'''

data = {
    'OrderID': [101, 102, 103, 104, 105, 106, 107, 108],
    'OrderDate': ['2025-10-01', '2025-10-01', '2025-10-02',
                  '2025-10-02', '2025-10-03', '2025-10-04',
                  '2025-10-04', '2025-10-05'],
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Laptop', 'Monitor',
                'Mouse', 'Webcam', 'Keyboard'],
    'Category': ['Electronics', 'Peripherals', 'Peripherals',
                 'Electronics', 'Electronics', 'Peripherals',
                 'Peripherals', 'Peripherals'],
    'Price': [1200, 25, 75, 1250, 300, 30, 50, 80],
    'Quantity': [2, 5, 3, 1, 2, 4, 1, 2]
}

df = pd.DataFrame(data)
df['OrderDate'] = pd.to_datetime(df['OrderDate'])
print(df.head())
print(df.columns)

   OrderID  OrderDate   Product     Category  Price  Quantity
0      101 2025-10-01    Laptop  Electronics   1200         2
1      102 2025-10-01     Mouse  Peripherals     25         5
2      103 2025-10-02  Keyboard  Peripherals     75         3
3      104 2025-10-02    Laptop  Electronics   1250         1
4      105 2025-10-03   Monitor  Electronics    300         2
Index(['OrderID', 'OrderDate', 'Product', 'Category', 'Price', 'Quantity'], dtype='object')


In [11]:
# -------------------- The Daily Top Product ----------------------
def get_daily_top_product(df: pd.DataFrame) -> list:
    ''' Function Name: get daily top product(df: pd.DataFrame) -> list
    Description:
    For each unique OrderDate, find the product that generated the highest total revenue (Price ×
    3
    Quantity). Return a list of product names corresponding to each unique date, ordered by ascending
    OrderDate.
    
    Input:
    • df: DataFrame containing atleast thecolumns OrderDate, Product, Price, andQuantity.
    The OrderDate column should be of datetime dtype (or parseable to datetime).
    
    Output:
    • List[str]: Product names — one per unique date (dates in ascending order).
    
    Notes / Tie-breaking:
    If two products on the same date have exactly the same total revenue, the tie is broken deterministically
    by choosing the product that appears first after sorting by revenue descending and then by product name
    ascending.'''
    
    df1 = df.copy()
    df1['Revenue'] = df['Price']*df['Quantity']
    print(f"Upadted Data Frame with Revenue Column :\n {df1}")
    print(f"\nlist of columns :{list(df1.columns)}")
    
    idx = df1.groupby('OrderDate')['Revenue'].idxmax()
    top_product = df1.loc[idx,['Product']]
    
    top_product = list(top_product['Product'])
    return top_product
    
if __name__ == "__main__":
    print(get_daily_top_product(df))


Upadted Data Frame with Revenue Column :
    OrderID  OrderDate   Product     Category  Price  Quantity  Revenue
0      101 2025-10-01    Laptop  Electronics   1200         2     2400
1      102 2025-10-01     Mouse  Peripherals     25         5      125
2      103 2025-10-02  Keyboard  Peripherals     75         3      225
3      104 2025-10-02    Laptop  Electronics   1250         1     1250
4      105 2025-10-03   Monitor  Electronics    300         2      600
5      106 2025-10-04     Mouse  Peripherals     30         4      120
6      107 2025-10-04    Webcam  Peripherals     50         1       50
7      108 2025-10-05  Keyboard  Peripherals     80         2      160

list of columns :['OrderID', 'OrderDate', 'Product', 'Category', 'Price', 'Quantity', 'Revenue']
['Laptop', 'Laptop', 'Monitor', 'Mouse', 'Keyboard']


# Matplotlib +  Seaborn

# References :
- https://www.w3schools.com/python/numpy