<a href="https://www.kaggle.com/code/sjagkoo7/numpy-pandas-matplotlib-seaborn?scriptVersionId=269481318" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/nifty50-stock-market-data/HDFCBANK.csv
/kaggle/input/nifty50-stock-market-data/GRASIM.csv
/kaggle/input/nifty50-stock-market-data/WIPRO.csv
/kaggle/input/nifty50-stock-market-data/stock_metadata.csv
/kaggle/input/nifty50-stock-market-data/BPCL.csv
/kaggle/input/nifty50-stock-market-data/INFY.csv
/kaggle/input/nifty50-stock-market-data/LT.csv
/kaggle/input/nifty50-stock-market-data/RELIANCE.csv
/kaggle/input/nifty50-stock-market-data/BRITANNIA.csv
/kaggle/input/nifty50-stock-market-data/INFRATEL.csv
/kaggle/input/nifty50-stock-market-data/HEROMOTOCO.csv
/kaggle/input/nifty50-stock-market-data/HINDUNILVR.csv
/kaggle/input/nifty50-stock-market-data/TATAMOTORS.csv
/kaggle/input/nifty50-stock-market-data/MM.csv
/kaggle/input/nifty50-stock-market-data/HDFC.csv
/kaggle/input/nifty50-stock-market-data/JSWSTEEL.csv
/kaggle/input/nifty50-stock-market-data/TITAN.csv
/kaggle/input/nifty50-stock-market-data/HINDALCO.csv
/kaggle/input/nifty50-stock-market-data/AXISBANK.csv
/kaggle/inpu

In [2]:
# just data reading
#data = pd.read_csv("/kaggle/input/factors-affecting-campus-placement/Placement_Data_Full_Class.csv")
data = pd.read_csv("/kaggle/input/nifty50-stock-market-data/TCS.csv")
data.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


Date Symbol Series  Prev Close    Open    High     Low    Last  \
0  2004-08-25    TCS     EQ      850.00  1198.7  1198.7  979.00  985.00   
1  2004-08-26    TCS     EQ      987.95   992.0   997.0  975.30  976.85   
2  2004-08-27    TCS     EQ      979.00   982.4   982.4  958.55  961.20   
3  2004-08-30    TCS     EQ      962.65   969.9   990.0  965.00  986.40   
4  2004-08-31    TCS     EQ      986.75   986.5   990.0  976.00  987.80   

    Close     VWAP    Volume      Turnover  Trades  Deliverable Volume  \
0  987.95  1008.32  17116372  1.725876e+15     NaN             5206360   
1  979.00   985.65   5055400  4.982865e+14     NaN             1294899   
2  962.65   969.94   3830750  3.715586e+14     NaN              976527   
3  986.75   982.65   3058151  3.005106e+14     NaN              701664   
4  988.10   982.18   2649332  2.602133e+14     NaN              695234   

   %Deliverble  
0       0.3042  
1       0.2561  
2       0.2549  
3       0.2294  
4       0.2624

# Numpy +  Pandas

In [3]:
#help(np.array)

In [4]:
def numpy_explore_part1():
    '''
    NumPy was created in 2005 by Travis Oliphant. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists. 
    NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
    This behavior is called locality of reference in computer science. It also has functions for working in domain of linear algebra, fourier transform, and matrices.")
    '''
    print("Welcome to Numpy Learning .......!")
    print(f"numpy version : {np.__version__}")
    
    # ---------------------- np.array --------------------------------
    print("\n---------------- np.array using list -------------------")
    numpy_list = np.array([1,2,3,4,5]) 
    print(f"numpy array using list : {numpy_list}")
    print(f"numpy_list  type : {type(numpy_list)}")
    print(f"numpy_list  dimension : {numpy_list.ndim}")

    print("\n---------------- np.array using tuple -------------------")
    numpy_tuple = np.array((1,2,3,4,5),dtype = float)
    print(f"numpy array using tuple : {numpy_tuple}")
    print(f"numpy_tuple  type : {type(numpy_tuple)}")
    print(f"numpy_tuple  dimension : {numpy_tuple.ndim}")
    
    print("\n---------------- 2-D array -------------------")
    two_D_array = np.array([[1,2,3,4],[5,6,7,8]])
    print(f"2-D numpy array : \n {two_D_array}")
    print(f"2-D numpy array  dimension : {two_D_array.ndim}")

    print("\n---------------- 3-D array -------------------")
    three_D_array =np.array([[[1,2,3,4],[5,6,7,8]] ,[[9,0,11,12],[14,15,16,17]]])
    print(f"3-D numpy array : \n {three_D_array}")
    
    print("\n---------------- Understading Indexing -------------------")
    print(f"Element on the 2nd row, 4th column in two_D_array : {two_D_array[1,3]}")
    print(f"Access the third element of the second array of the first array:{three_D_array[0,1,2]}")
    print(f"sum of {numpy_list[1]} , {numpy_tuple[2]} and {two_D_array[0][3]}  : {numpy_list[1]+ numpy_tuple[2]+two_D_array[0][3]}")

    print("\n------------- Slicing [start:end:step] ----------------------------")
    print(f"Slicing with step 2 Original : {numpy_list} Post slicing : {numpy_list[1:4:2]}")
    print(f"2-D slicing :\n{ two_D_array[0:2, 1:3]}")
    return None

#program execution starts from here
if __name__ ==  "__main__":
    numpy_explore_part1()

Welcome to Numpy Learning .......!
numpy version : 1.26.4

---------------- np.array using list -------------------
numpy array using list : [1 2 3 4 5]
numpy_list  type : <class 'numpy.ndarray'>
numpy_list  dimension : 1

---------------- np.array using tuple -------------------
numpy array using tuple : [1. 2. 3. 4. 5.]
numpy_tuple  type : <class 'numpy.ndarray'>
numpy_tuple  dimension : 1

---------------- 2-D array -------------------
2-D numpy array : 
 [[1 2 3 4]
 [5 6 7 8]]
2-D numpy array  dimension : 2

---------------- 3-D array -------------------
3-D numpy array : 
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9  0 11 12]
  [14 15 16 17]]]

---------------- Understading Indexing -------------------
Element on the 2nd row, 4th column in two_D_array : 8
Access the third element of the second array of the first array:7
sum of 2 , 3.0 and 4  : 9.0

------------- Slicing [start:end:step] ----------------------------
Slicing with step 2 Original : [1 2 3 4 5] Post slicing : [2 4]
2-D sl

In [5]:
#help(pd.DataFrame)

In [6]:
def pandas_explore_part1():
    '''
    Pandas was created by Wes McKinney in 2008
    '''
    
    print("Welcome to Pandas Learning .......!")
    print(f"pandas version : {pd.__version__}\n")

    # ---------------------- pd.series --------------------------------
    print(f"Pandas Series :\n{pd.Series([3.5,7.2,5.0])}")
    
    print(f"\nPandas Series with custom index:\n{pd.Series([3.5,7.2,5.0],index=['x','y','z'])}")
    
    dic_var = {'Sub1':'Math','sub2':'Python','sub3':'TSA'}
    print(f"\nPandas Series using dictionary :\n{pd.Series(dic_var)}")
    
    print(f"\nPanas Series using custom filter from dictionary :\n{pd.Series(dic_var,index=['Sub1','sub2'])}")

    #----------------------- pd.DataFrame ------------------------------
    student_details = pd.DataFrame({'Name':['Amardeep Kumar','PP Singh','GG Gandhi','TT Singh'],
                 'Course' :['M.TECH AI','P.HD','MBA','B.TECH'],
                 'College':['IIT Madras','IIT Kanpur','IIT Mumbai','IIT Goa'],
                 'Year':['2025','2024','2023','2021'],
                 'Exam Score':[200,300,400,500]},index=['S1','S2','S3','S4'])
    print(f"\nstudent_details dataframe :\n{student_details}")

    #-------loc syntax : df.loc[row_labels, column_labels] -----------------
    person_details = pd.DataFrame({
    "Name": ["Asha", "Bala", "Chetan", "Divya"],
    "Marks": [85, 90, 78, 92],
    "City": ["Chennai", "Pune", "Delhi", "Vizag"]}, index=["s1", "s2", "s3", "s4"])
    print(f"\nperson_details dataframe :\n{person_details}")
    print(f"\nusing loc :\n{person_details.loc[['s1'],['Name','Marks']]}")
    print(f"\napplying filter using loc :\n{person_details.loc[person_details['Marks']>80,['Name','Marks']]}")
    
    return None

if __name__ == "__main__":
    pandas_explore_part1()

Welcome to Pandas Learning .......!
pandas version : 2.2.3

Pandas Series :
0    3.5
1    7.2
2    5.0
dtype: float64

Pandas Series with custom index:
x    3.5
y    7.2
z    5.0
dtype: float64

Pandas Series using dictionary :
Sub1      Math
sub2    Python
sub3       TSA
dtype: object

Panas Series using custom filter from dictionary :
Sub1      Math
sub2    Python
dtype: object

student_details dataframe :
              Name     Course     College  Year  Exam Score
S1  Amardeep Kumar  M.TECH AI  IIT Madras  2025         200
S2        PP Singh       P.HD  IIT Kanpur  2024         300
S3       GG Gandhi        MBA  IIT Mumbai  2023         400
S4        TT Singh     B.TECH     IIT Goa  2021         500

person_details dataframe :
      Name  Marks     City
s1    Asha     85  Chennai
s2    Bala     90     Pune
s3  Chetan     78    Delhi
s4   Divya     92    Vizag

using loc :
    Name  Marks
s1  Asha     85

applying filter using loc :
     Name  Marks
s1   Asha     85
s2   Bala     90


# Matplotlib +  Seaborn

# References :
- https://www.w3schools.com/python/numpy