<a href="https://www.kaggle.com/code/sjagkoo7/tensorflow-basics-example-3?scriptVersionId=168575837" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

# import packages
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tensorflow as tf # machine learning

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

2024-03-24 15:57:44.701217: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-24 15:57:44.701376: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-24 15:57:44.873483: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


# Question 1 :
### Create a scalar and vector which are immutable 
* the scaler should be of dtype "int32"
* the vector should be of the shape (3).and type of dtype "int32"
* Assign the scaler to the variable `"scaler"`
* Assign the vector to the variable `"vector"`

In [2]:
def scalar_and_vector():
    scaler = tf.constant(123,dtype=tf.int32)
    vector = tf.constant([5,6,2],dtype=tf.int32)
    return [scaler, vector]

In [3]:
scalar_and_vector = scalar_and_vector()
scalar_and_vector

[<tf.Tensor: shape=(), dtype=int32, numpy=123>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 6, 2], dtype=int32)>]

# Question 2 :
### Create a matrix and tensor which are immutable 
* the matrix should be of the shape (3,2).and of dtype "float32"
* the tensor should be of the shape (4,3,3).and of dtype "int32"
* Assign the scaler to the variable `"matrix"`
* Assign the vector to the variable `"tensor"`

In [4]:
def matrix_and_tensor():
    matrix=tf.constant([ [1.0,2.0] , [2.0,3.0],[3.0,4.0] ],dtype=tf.float32)
    tensor = tf.constant([ [[1,2,3],[2,3,4],[4,5,6]] ,[[6,7,8],[8,9,10],[10,11,12]], [[12,13,14],[14,15,16],[16,17,18]], [[18,19,20],[20,21,22],[22,23,24]] ])
    return [matrix,tensor]

In [5]:
matrix_and_tensor = matrix_and_tensor()
matrix_and_tensor

[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 2.],
        [2., 3.],
        [3., 4.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 3, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 2,  3,  4],
         [ 4,  5,  6]],
 
        [[ 6,  7,  8],
         [ 8,  9, 10],
         [10, 11, 12]],
 
        [[12, 13, 14],
         [14, 15, 16],
         [16, 17, 18]],
 
        [[18, 19, 20],
         [20, 21, 22],
         [22, 23, 24]]], dtype=int32)>]

# Question 3:
### perform the following operations
* Create a random tensor from a uniform distribution of shape (5,3,3,2) with values between 0 and 1 with the seed value as 32 and assign the tensor to the variable "random_1"
* Create a random tensor from a uniform distribution of shape (5,3,3,2) with values between 0 and 1 and assign the tensor to the variable "random_1"

In [6]:
def random_tensor():
    tf.random.set_seed(32)
    random_1=tf.random.uniform(shape=(5,3,3,2),minval=0,maxval=1)
    random_2=tf.random.uniform(shape=(5,3,3,2),minval=0,maxval=1)
    return [random_1,random_2]

In [7]:
random_tensor=random_tensor()
random_tensor

[<tf.Tensor: shape=(5, 3, 3, 2), dtype=float32, numpy=
 array([[[[0.54520595, 0.13372338],
          [0.45232666, 0.15582252],
          [0.9621073 , 0.8151462 ]],
 
         [[0.4068215 , 0.9565903 ],
          [0.5532354 , 0.44936454],
          [0.01469815, 0.86204493]],
 
         [[0.12014258, 0.91072273],
          [0.00848019, 0.62772846],
          [0.8167286 , 0.98235905]]],
 
 
        [[[0.06410611, 0.17873585],
          [0.07358396, 0.95524645],
          [0.5906956 , 0.3774085 ]],
 
         [[0.9427308 , 0.32449841],
          [0.05033565, 0.6481848 ],
          [0.97997856, 0.7848562 ]],
 
         [[0.8223983 , 0.25406194],
          [0.21289039, 0.18566561],
          [0.18804717, 0.5875702 ]]],
 
 
        [[[0.45183384, 0.5508704 ],
          [0.18366766, 0.55480397],
          [0.72248566, 0.66862214]],
 
         [[0.46865964, 0.50943816],
          [0.61882794, 0.5858562 ],
          [0.7246859 , 0.88589907]],
 
         [[0.7049539 , 0.00409675],
          [0.05

# Question 4 :
### Perform matrix multiplication
#### Given two matrices matrix1,matrix2 with identical shape (5,3), find a way to perform matrix multiplication with resultant shape of (5,5)
* Assign the resultant vector to the variable "resultant_vector"

In [8]:
def matrix_multiplication(matrix1,matrix2):
    resultant_vector= tf.matmul(matrix1,matrix2)
    return resultant_vector

In [9]:
matrix1=tf.constant([[1,2,3],[3,4,5],[5,6,7],[7,8,9],[9,10,11]])
matrix2=tf.constant([[11,12,13,14,15],[15,16,17,18,19],[19,20,21,22,23]])
matrix_multiplication=matrix_multiplication(matrix1,matrix2)
matrix_multiplication

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 98, 104, 110, 116, 122],
       [188, 200, 212, 224, 236],
       [278, 296, 314, 332, 350],
       [368, 392, 416, 440, 464],
       [458, 488, 518, 548, 578]], dtype=int32)>

# Question 5:
### Aggregation , find the followings for the given `"tensor_1"`
* minimum and assign the value to the variable `"min_val"`
* maximum and assign the value to the variable `"max_val"`
* mean and assign the value to the variable `"mean_val"`
* sum and assign the value to the variable `"sum_val"`

In [10]:
def perform_aggregate(tensor_1):
    min_val=tf.reduce_min(tensor_1)
    max_val=tf.reduce_max(tensor_1)
    mean_val=tf.reduce_mean(tensor_1)
    sum_val=tf.reduce_sum(tensor_1)
    return [min_val,max_val,mean_val,sum_val]

In [11]:
tensor_1=tf.constant([ [[1,2,3],[2,3,4],[4,5,6]] ,[[6,7,8],[8,9,10],[10,11,12]], [[12,13,14],[14,15,16],[16,17,18]], [[18,19,20],[20,21,22],[22,23,24]] ])
perform_aggregate=perform_aggregate(tensor_1)
perform_aggregate

[<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=24>,
 <tf.Tensor: shape=(), dtype=int32, numpy=12>,
 <tf.Tensor: shape=(), dtype=int32, numpy=435>]

# Question 6 :
### Find the minimum and maximum element index of each vector for the given tensor `"tensor_1'`
* Assign the maximum element indexes to the variable `"max_pos"`
* Assign the minimum element indexes to the variable `"max_pos"`
* The indexes should be of the type `"numpy array"`

In [12]:
def min_max_position(tensor_1):
    max_pos = tf.argmax(tensor_1,axis=-1)
    min_pos = tf.argmin(tensor_1,axis=-1)
    return [max_pos,min_pos]

In [13]:
tensor_1=tf.constant([ [[1,2,3],[2,3,4],[4,5,6]] ,[[6,7,8],[8,9,10],[10,11,12]], [[12,13,14],[14,15,16],[16,17,18]], [[18,19,20],[20,21,22],[22,23,24]] ])
min_max_position=min_max_position(tensor_1)
min_max_position

[<tf.Tensor: shape=(4, 3), dtype=int64, numpy=
 array([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])>,
 <tf.Tensor: shape=(4, 3), dtype=int64, numpy=
 array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])>]

# Question 7:
### one hot encode the given tensor `"onehot_tensor"` and assign  then encoded tensor to the variable `"encoded_tensor"`
* the input tensor might contain values between 0-9
* the returned tensor should be of dtype "int32"

In [14]:
def one_hot_encode_tensor(onehot_tensor):
    depth=10
    encoded_tensor = tf.one_hot(onehot_tensor,depth,dtype=tf.int32)
    return encoded_tensor

In [15]:
onehot_tensor = [0, 2, 4, 1, 3, 5, 0, 2, 9]
one_hot_encode_tensor = one_hot_encode_tensor(onehot_tensor)
one_hot_encode_tensor

<tf.Tensor: shape=(9, 10), dtype=int32, numpy=
array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int32)>