<a href="https://www.kaggle.com/code/sjagkoo7/tensorflow-basics-example-1?scriptVersionId=167559523" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# TensorFlow Session Steps :
   * Importing the desired library
   * Intializing the variables and constants
   * Placeholders for performing the compuatation
   * Intializing a session on CPU or GPU -- no longer required in TensorFlow 2.x
   * Performing the compuatation
   * Display results
   * Close the sessions -- no longer required in TensorFlow 2.x

In [2]:
#import tensorflow as tf # this is for TensorFlow 2.x with eager execution  enabled
import tensorflow.compat.v1 as tf # this is for TensorFlow 2.x with eager execution disabled,means we can execute TensorFlow 1.x method like Session etc.
tf.disable_eager_execution() # disables eager execution, making TensorFlow operate in graph mode.
#tf.config.run_functions_eagerly(True) --  enables eager execution of functions.
#print(tf.executing_eagerly()) -- returns True if eager execution is enabled and False otherwise

2024-03-18 06:02:54.411926: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-18 06:02:54.412031: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-18 06:02:54.568691: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [3]:
#Intializing the variables and constants
#help(tf.constant)
a=tf.constant([2])
b=tf.constant([3])

In [4]:
#Placeholders for performing the compuatation
#help(tf.add)
c=tf.add(a,b)
#c=a+b

In [5]:
# in TensorFlow 2.x , Session is deprecated , now directly evaluate tensors using .numpy() method

#Intializing a session on CPU or GPU
# session=tf.Session()

#Display results
# result=session.run(c)
# print(result)

#Close the sessions
# session.close()

#to avoid close every time using below approach it close session automatically.
with tf.Session() as session:
    result=session.run(c)
    print(result)

[5]


In [6]:
# Display results
#print(c.numpy())

# Tensors - Scaler , Vector And Matrix

In [7]:
Scaler=tf.constant([2])
Vector=tf.constant([5,6,2])
Matrix=tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Tensor=tf.constant([ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ])

with tf.Session() as session:
    scaler_value = session.run(Scaler)
    vector_value = session.run(Vector)
    matrix_value = session.run(Matrix)
    tensor_value = session.run(Tensor)
    # Print the values
    print("Scaler (1 entry):\n", scaler_value)
    print("\nVector (3 entries):\n", vector_value)
    print("\nMatrix (3x3 entries):\n", matrix_value)
    print("\nTensor (3x3x3 entries):\n", tensor_value)
    
# print("Scaler (1 entry):\n",Scaler.numpy())
# print("\nVector (3 entries):\n",Vector.numpy())
# print("\nMatrix (3x3 entries):\n",Matrix.numpy())
# print("\nTensor (3x3x3 entries):\n",Tensor.numpy())

Scaler (1 entry):
 [2]

Vector (3 entries):
 [5 6 2]

Matrix (3x3 entries):
 [[1 2 3]
 [2 3 4]
 [3 4 5]]

Tensor (3x3x3 entries):
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]]


In [8]:
Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

first_operation=tf.add(Matrix_one,Matrix_two)
second_operation=Matrix_one+Matrix_two
third_operation=tf.matmul(Matrix_one,Matrix_two)

with tf.Session() as session:
    first_operation = session.run(first_operation)
    second_operation = session.run(second_operation)
    third_operation = session.run(third_operation)
    print("Using TensorFlow functions:\n",first_operation)
    print("\nUsing normal experssion :\n",second_operation)
    print("\nUsing TensorFlow matmul functions :\n",third_operation)


# print("Using TensorFlow functions:\n",first_operation.numpy())
# print("\nUsing normal experssion :\n",second_operation.numpy())
# print("\nUsing TensorFlow matmul functions :\n",third_operation.numpy())

Using TensorFlow functions:
 [[3 4 5]
 [4 5 6]
 [5 6 7]]

Using normal experssion :
 [[3 4 5]
 [4 5 6]
 [5 6 7]]

Using TensorFlow matmul functions :
 [[12 12 12]
 [18 18 18]
 [24 24 24]]


# Constant , Variables And Placeholders

#### Constants:
* Constants are tensors whose values cannot be changed. They are typically used to hold fixed values that are known before the graph is executed.

#### Variables:
* Variables are tensors whose values can be changed. They are typically used to hold trainable parameters of a model, such as weights and biases.
* Before using variables, you must initialize them.

#### Placeholders:
* Placeholders are tensors used to feed external data into the TensorFlow graph. They are typically used for inputs to the model.
* Unlike constants and variables, placeholders do not have initial values and do not hold any data.They serve as a placeholder for data that will be provided later during the execution of the graph.

In [9]:
#Variables
tf.disable_v2_behavior()

one=tf.constant(1)
state=tf.Variable(0, dtype=tf.int32)

new_value=tf.add(state,one)
update=tf.assign(state,new_value) # tf.assign() is depreciated in TensorFlow 2.x.

init_op=tf.global_variables_initializer() #tf.intialize_all_variables() is depreciated in TensorFlow 2.x.

# Run the session
with tf.Session() as session: #Session is deprecated in TensorFlow 2.x . So using compat.v1 for version compability for TensorFlow 1.x
    # Initialize variables
    session.run(init_op)
    # Update the state variable
    for _ in range(3):
        session.run(update)
        print(session.run(state))

1
2
3


In [10]:
#placeholders
a=tf.placeholder(tf.float32)
b=a*2

In [11]:
with tf.Session() as session:
    result=session.run(b,feed_dict={a:3.5})
    print(result)

7.0


In [12]:
dictionary={a:[ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }
with tf.Session() as session:
    result=session.run(b,feed_dict=dictionary)
    print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]
