<a href="https://www.kaggle.com/code/sjagkoo7/tensorflow-learning?scriptVersionId=164482695" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# TensorFlow Session Steps :
   * Importing the desired library
   * Intializing the variables and constants
   * Placeholders for performing the compuatation
   * Intializing a session on CPU or GPU -- no longer required in TensorFlow 2.x
   * Performing the compuatation
   * Display results
   * Close the sessions -- no longer required in TensorFlow 2.x

In [2]:
# importing tensorflow 
import tensorflow as tf 

2024-02-27 05:05:07.208202: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-27 05:05:07.208376: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-27 05:05:07.409317: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [3]:
#Intializing the variables and constants
#help(tf.constant)
a=tf.constant([2])
b=tf.constant([3])

In [4]:
#Placeholders for performing the compuatation
#help(tf.add)
c=tf.add(a,b)
#c=a+b

In [5]:
# in TensorFlow 2.x , Session is deprecated , now directly evaluate tensors using .numpy() method

#Intializing a session on CPU or GPU
#session=tf.Session()

#Display results
# result=session.run(c)
# print(result)

#Close the sessions
# session.close()

#to avoid close every time using below approach it close session automatically.
# with tf.Session() as session:
#     result=session.run(c)
#     print(result)

In [6]:
# Display results
print(c.numpy())

[5]


# Tensors - Scaler , Vector And Matrix

In [7]:
Scaler=tf.constant([2])
Vector=tf.constant([5,6,2])
Matrix=tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Tensor=tf.constant([ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ])
print("Scaler (1 entry):\n",Scaler.numpy())
print("\nVector (3 entries):\n",Vector.numpy())
print("\nMatrix (3x3 entries):\n",Matrix.numpy())
print("\nTensor (3x3x3 entries):\n",Tensor.numpy())

Scaler (1 entry):
 [2]

Vector (3 entries):
 [5 6 2]

Matrix (3x3 entries):
 [[1 2 3]
 [2 3 4]
 [3 4 5]]

Tensor (3x3x3 entries):
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]]


In [8]:
Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])
first_operation=tf.add(Matrix_one,Matrix_two)
second_operation=Matrix_one+Matrix_two
third_operation=tf.matmul(Matrix_one,Matrix_two)
print("Using TensorFlow functions:\n",first_operation.numpy())
print("\nUsing normal experssion :\n",second_operation.numpy())
print("\nUsing TensorFlow matmul functions :\n",third_operation.numpy())

Using TensorFlow functions:
 [[3 4 5]
 [4 5 6]
 [5 6 7]]

Using normal experssion :
 [[3 4 5]
 [4 5 6]
 [5 6 7]]

Using TensorFlow matmul functions :
 [[12 12 12]
 [18 18 18]
 [24 24 24]]


# Variables And Placeholders